### ISSUE TITLE
Path is getting logged

### ISSUE THREAD

**Issue by Mark-H** [jpdevries/blockdown#3]
Stray debug statement?  https://github.com/jpdevries/blockdown/blob/master/core/components/blockdown/elements/plugins/blockdown.plugin.php#L11

**Comment by jpdevries** [comment]
whoops

**Comment by Mark-H** [comment]
Hey @jpdevries could you push a tag/release to blockdown? Kinda annoying, as it happens on any page that has ContentBlocks on it ;)
